namespace Application.Features.Inventory;

// ===== Stocktake (physical count / cycle count) =====

public class StocktakeDto
{
    public Guid Id { get; set; }
    public string StocktakeNumber { get; set; } = string.Empty;

    public Guid WarehouseId { get; set; }
    public string WarehouseNameEn { get; set; } = string.Empty;
    public string WarehouseNameAr { get; set; } = string.Empty;

    public string Type { get; set; } = string.Empty;        // Full | Cycle
    public string ScopeType { get; set; } = string.Empty;   // All | Category | Products
    public Guid? ScopeCategoryId { get; set; }
    public string? ScopeCategoryNameEn { get; set; }
    public string? ScopeCategoryNameAr { get; set; }

    public string Status { get; set; } = string.Empty;

    public Guid? CreatedById { get; set; }
    public string? CreatedByName { get; set; }
    public DateTime CreatedAt { get; set; }

    public DateTime? StartedAt { get; set; }
    public DateTime? CompletedAt { get; set; }

    public Guid? ApprovedById { get; set; }
    public string? ApprovedByName { get; set; }
    public DateTime? ApprovedAt { get; set; }

    public string? Notes { get; set; }

    // Summary counters (computed) — used by the list view.
    public int TotalLines { get; set; }
    public int CountedLines { get; set; }
    public int MatchedLines { get; set; }
    public int FlaggedLines { get; set; }

    public List<StocktakeLineDto> Lines { get; set; } = new();
}

public class StocktakeLineDto
{
    public Guid Id { get; set; }
    public Guid UnitId { get; set; }
    public string UnitBarcode { get; set; } = string.Empty;
    public string ProductNameEn { get; set; } = string.Empty;
    public string ProductNameAr { get; set; } = string.Empty;
    public string ProductCode { get; set; } = string.Empty;
    public string UnitOfMeasureNameEn { get; set; } = string.Empty;
    public string UnitOfMeasureNameAr { get; set; } = string.Empty;
    public int UnitBaseQuantity { get; set; } = 1;

    public int SystemQuantity { get; set; }
    public int? CountedQuantity { get; set; }
    public int Difference { get; set; }

    public string LineStatus { get; set; } = string.Empty;
    public string? AdjustmentType { get; set; }
    public Guid? GeneratedAdjustmentId { get; set; }
    public string? GeneratedAdjustmentNumber { get; set; }

    public string? Notes { get; set; }
}

/// <summary>Creates a stocktake header in Draft. Lines are generated by Start.</summary>
public class CreateStocktakeRequest
{
    public Guid WarehouseId { get; set; }
    public string Type { get; set; } = string.Empty;        // Full | Cycle
    public string ScopeType { get; set; } = "All";          // All | Category | Products
    public Guid? ScopeCategoryId { get; set; }
    public List<Guid>? UnitIds { get; set; }                // for ScopeType = Products
    public string? Notes { get; set; }
}

/// <summary>Progressively saves counted quantities while a stocktake is InProgress.</summary>
public class SaveStocktakeCountsRequest
{
    public List<StocktakeCountLineRequest> Lines { get; set; } = new();
}

public class StocktakeCountLineRequest
{
    public Guid LineId { get; set; }
    public int CountedQuantity { get; set; }
    public string? Notes { get; set; }
}

/// <summary>
/// Submits the per-line adjustment type the manager picked, then approves the
/// stocktake (generating adjustments). Positive-difference lines default to
/// CorrectionAdd when no type is supplied.
/// </summary>
public class ApproveStocktakeRequest
{
    public List<ApproveStocktakeLineRequest> Lines { get; set; } = new();
}

public class ApproveStocktakeLineRequest
{
    public Guid LineId { get; set; }
    public string? AdjustmentType { get; set; }   // Loss | Theft | Damage | Expiry | CorrectionAdd
}
